[package]
name = "did-webplus-ssi"
version = "0.1.0"
authors = ["Victor Dods <victor.dods@ledgerdomain.com>"]
edition = "2021"

[dependencies]
did-webplus-core = { path = "../core" }
did-webplus-resolver = { path = "../resolver" }
mbx = "0.1.1"
selfhash = { version = "0.5.1", features = ["mbx"] }
signature-dyn = "0.1.0"
ssi-dids = { version = "0.2.1", default-features = false }
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.94"
chrono = "0.4.42"
ctor = "0.4.1"
did-webplus-doc-storage-sqlite = { path = "../doc-storage-sqlite" }
did-webplus-doc-store = { path = "../doc-store" }
did-webplus-software-wallet = { path = "../software-wallet" }
did-webplus-vdr-lib = { path = "../vdr-lib", features = ["postgres"] }
did-webplus-wallet = { path = "../wallet" }
did-webplus-wallet-storage-sqlite = { path = "../wallet-storage-sqlite" }
did-webplus-wallet-store = { path = "../wallet-store" }
dotenvy = "0.15.7"
ed25519-dalek = "2.2.0"
iref = "3.2.2"
k256 = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.8.2", features = ["sqlite"] }
ssi-claims = { version = "0.4.0", features = ["webplus"] }
ssi-jwk = "0.3.2"
ssi-jws = "0.3.1"
ssi-vc = "0.6.1"
ssi-verification-methods = "0.1.3"
static-iref = "3.0.0"
storage-traits = { path = "../../storage-traits" }
test-util = { path = "../../test-util" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
xsd-types = "0.9.5"
