[package]
name = "did-webplus-wallet"
version = "0.1.0"
authors = ["Victor Dods <victor.dods@ledgerdomain.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.80"
did-webplus-core = { path = "../core" }
did-webplus-doc-store = { path = "../doc-store" }
did-webplus-wallet-store = { path = "../wallet-store" }
signature-dyn = "0.1.0"
thiserror = "1.0.60"
time = { version = "0.3", features = ["serde"] }

[dev-dependencies]
ctor = "0.4.1"
dotenvy = "0.15.7"
test-util = { path = "../../test-util" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
